import { AST_NODE_TYPES, type TSESTree } from "@typescript-eslint/utils"

import { createRule, stringValue } from "../utils"

const FEDERATION_GLOBALS = new Set(["__federation__", "__federation_shared__", "__federation_method_getRemote", "__federation_method_setRemote", "__federation_method_ensure", "__federation_method_unwrapDefault", "__federation_method_wrapDefault", "__webpack_share_scopes__", "__webpack_init_sharing__", "__webpack_require__", "__VITE_PRELOAD__"])

type MessageIds = "federationImport" | "federationApi" | "federationGlobal"

function isFederationSource(source: string | null): boolean {
  return source !== null && (source === "@module-federation" || source.startsWith("@module-federation/"))
}

export default createRule<[], MessageIds>({
  name: "no-direct-module-federation",
  meta: {
    type: "problem",
    docs: { description: "Disallow importing or calling Module Federation from MFE application code; @platform/vite and @platform/host own federation." },
    messages: {
      federationImport: "MFE code must not import `{{source}}`: Module Federation is generated by @platform/vite and driven by @platform/host. Expose widgets with `createWidget` and navigate with `useNavigation()` instead.",
      federationApi: "`{{name}}` is a Module Federation runtime API; remotes are loaded by the host, never by MFE code.",
      federationGlobal: "`{{name}}` is a federation implementation detail; MFE code must not read it.",
    },
    schema: [],
  },
  defaultOptions: [],
  create(context) {
    const federationLocals = new Set<string>()
    const checkSource = (node: TSESTree.Node, source: string | null) => {
      if (isFederationSource(source)) context.report({ node, messageId: "federationImport", data: { source: source! } })
    }
    return {
      ImportDeclaration(node) {
        const source = String(node.source.value)
        checkSource(node, source)
        if (isFederationSource(source)) {
          for (const specifier of node.specifiers) federationLocals.add(specifier.local.name)
        }
      },
      ImportExpression(node) {
        checkSource(node, stringValue(node.source))
      },
      ExportAllDeclaration(node) {
        checkSource(node, String(node.source.value))
      },
      ExportNamedDeclaration(node) {
        if (node.source) checkSource(node, String(node.source.value))
      },
      CallExpression(node) {
        const callee = node.callee
        if (callee.type === AST_NODE_TYPES.Identifier && callee.name === "require") {
          checkSource(node, stringValue(node.arguments[0]))
          return
        }
        if (callee.type === AST_NODE_TYPES.Identifier && federationLocals.has(callee.name)) {
          context.report({ node, messageId: "federationApi", data: { name: callee.name } })
        } else if (callee.type === AST_NODE_TYPES.MemberExpression && callee.object.type === AST_NODE_TYPES.Identifier && federationLocals.has(callee.object.name) && callee.property.type === AST_NODE_TYPES.Identifier) {
          context.report({ node, messageId: "federationApi", data: { name: `${callee.object.name}.${callee.property.name}` } })
        }
      },
      Program(program) {
        const scope = context.sourceCode.getScope(program)
        for (const reference of scope.through) {
          const name = reference.identifier.name
          if (FEDERATION_GLOBALS.has(name)) context.report({ node: reference.identifier, messageId: "federationGlobal", data: { name } })
        }
      },
      MemberExpression(node) {
        if (node.computed || node.property.type !== AST_NODE_TYPES.Identifier) return
        if (!FEDERATION_GLOBALS.has(node.property.name)) return
        if (node.object.type === AST_NODE_TYPES.Identifier && ["window", "globalThis", "self"].includes(node.object.name)) {
          context.report({ node, messageId: "federationGlobal", data: { name: node.property.name } })
        }
      },
    }
  },
})
