import { matchesAny } from "../../glob"
import { createRule, filenameOf, stringValue } from "../utils"

export const GENERATED_PATTERNS = [
  "**/routeTree.gen.ts",
  "**/*.gen.ts",
  "**/*.gen.tsx",
  "**/.platform/**",
  "**/platform-manifest.json",
]

const BANNER_RE = /prettier-ignore-start|@ts-nocheck|generated by|noformat|eslint-disable/i
const PLATFORM_INTERNAL_RE = /(^|\/)\.platform\//

type Options = [{ patterns?: string[] }]
type MessageIds = "generatedFile" | "missingBanner" | "internalImport"

export default createRule<Options, MessageIds>({
  name: "no-generated-file-edits",
  meta: {
    type: "problem",
    docs: {
      description:
        "Generated files (routeTree.gen.ts, .platform/*, platform-manifest.json) are never edited or imported by hand.",
    },
    messages: {
      generatedFile:
        "`{{file}}` is generated by the platform tooling and must stay in the lint ignores; regenerate it with `platform dev`/`platform build` instead of editing it.",
      missingBanner:
        "`{{file}}` looks hand-written: generated files start with a generator banner (`/* prettier-ignore-start */`, `// @ts-nocheck` or `Generated by`). Delete it and let the tooling regenerate it.",
      internalImport:
        "Importing `{{source}}` reaches into `.platform/` internals (generated entry, cache, manifest). Import from `@platform/react` or your own sources instead.",
    },
    schema: [
      {
        type: "object",
        properties: {
          patterns: {
            type: "array",
            items: { type: "string" },
            description: "Additional generated-file globs.",
          },
        },
        additionalProperties: false,
      },
    ],
  },
  defaultOptions: [{ patterns: [] }],
  create(context, [options]) {
    const filename = filenameOf(context)
    const patterns = [...GENERATED_PATTERNS, ...(options.patterns ?? [])]
    const generated = matchesAny(filename, patterns)
    const file = filename.slice(filename.lastIndexOf("/") + 1)
    return {
      Program(program) {
        if (!generated) return
        context.report({ node: program, messageId: "generatedFile", data: { file } })
        const head = context.sourceCode.lines.slice(0, 5).join("\n")
        if (!BANNER_RE.test(head))
          context.report({ node: program, messageId: "missingBanner", data: { file } })
      },
      ImportDeclaration(node) {
        const source = String(node.source.value)
        if (PLATFORM_INTERNAL_RE.test(source))
          context.report({ node, messageId: "internalImport", data: { source } })
      },
      ImportExpression(node) {
        const source = stringValue(node.source)
        if (source && PLATFORM_INTERNAL_RE.test(source))
          context.report({ node, messageId: "internalImport", data: { source } })
      },
    }
  },
})
