/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteDocsRouteImport } from './routes/_site/docs'
import { Route as SiteDocsSplatRouteImport } from './routes/_site/docs/$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsRoute = SiteDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsSplatRoute = SiteDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/docs': typeof SiteDocsRouteWithChildren
  '/docs/$': typeof SiteDocsSplatRoute
}
export interface FileRoutesByTo {
  '/docs': typeof SiteDocsRouteWithChildren
  '/': typeof SiteIndexRoute
  '/docs/$': typeof SiteDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/docs': typeof SiteDocsRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_site/docs/$': typeof SiteDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/docs' | '/' | '/docs/$'
  id: '__root__' | '/_site' | '/_site/docs' | '/_site/' | '/_site/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs': {
      id: '/_site/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof SiteDocsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs/$': {
      id: '/_site/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof SiteDocsSplatRouteImport
      parentRoute: typeof SiteDocsRoute
    }
  }
}

interface SiteDocsRouteChildren {
  SiteDocsSplatRoute: typeof SiteDocsSplatRoute
}

const SiteDocsRouteChildren: SiteDocsRouteChildren = {
  SiteDocsSplatRoute: SiteDocsSplatRoute,
}

const SiteDocsRouteWithChildren = SiteDocsRoute._addFileChildren(
  SiteDocsRouteChildren,
)

interface SiteRouteChildren {
  SiteDocsRoute: typeof SiteDocsRouteWithChildren
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDocsRoute: SiteDocsRouteWithChildren,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
