/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WellsRouteImport } from './routes/wells'
import { Route as SettingsCustomRouteImport } from './routes/settings/custom'
import { Route as WellsIndexRouteImport } from './routes/wells/index'
import { Route as WellsWellIdRouteImport } from './routes/wells/$wellId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsRoute = WellsRouteImport.update({
  id: '/wells',
  path: '/wells',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCustomRoute = SettingsCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => SettingsRoute,
} as any)
const WellsIndexRoute = WellsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WellsRoute,
} as any)
const WellsWellIdRoute = WellsWellIdRouteImport.update({
  id: '/$wellId',
  path: '/$wellId',
  getParentRoute: () => WellsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wells': typeof WellsRouteWithChildren
  '/settings/custom': typeof SettingsCustomRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells/': typeof WellsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/custom': typeof SettingsCustomRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells': typeof WellsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wells': typeof WellsRouteWithChildren
  '/settings/custom': typeof SettingsCustomRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells/': typeof WellsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/wells'
    | '/settings/custom'
    | '/wells/$wellId'
    | '/wells/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/settings/custom' | '/wells/$wellId' | '/wells'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/wells'
    | '/settings/custom'
    | '/wells/$wellId'
    | '/wells/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WellsRoute: typeof WellsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells': {
      id: '/wells'
      path: '/wells'
      fullPath: '/wells'
      preLoaderRoute: typeof WellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/custom': {
      id: '/settings/custom'
      path: '/custom'
      fullPath: '/settings/custom'
      preLoaderRoute: typeof SettingsCustomRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/wells/': {
      id: '/wells/'
      path: '/'
      fullPath: '/wells/'
      preLoaderRoute: typeof WellsIndexRouteImport
      parentRoute: typeof WellsRoute
    }
    '/wells/$wellId': {
      id: '/wells/$wellId'
      path: '/$wellId'
      fullPath: '/wells/$wellId'
      preLoaderRoute: typeof WellsWellIdRouteImport
      parentRoute: typeof WellsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsCustomRoute: typeof SettingsCustomRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCustomRoute: SettingsCustomRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WellsRouteChildren {
  WellsWellIdRoute: typeof WellsWellIdRoute
  WellsIndexRoute: typeof WellsIndexRoute
}

const WellsRouteChildren: WellsRouteChildren = {
  WellsWellIdRoute: WellsWellIdRoute,
  WellsIndexRoute: WellsIndexRoute,
}

const WellsRouteWithChildren = WellsRoute._addFileChildren(WellsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WellsRoute: WellsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
