import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, relative } from "node:path"

import { PlatformError } from "@platform-internal/core"

import { ensurePlatformDir } from "./identity"
import type { ResolvedPlatformConfig } from "./resolve-config"

export const GENERATED_BANNER = "// Generated by @platform/vite — do not edit. Inspect freely."

function toImportPath(from: string, to: string): string {
  const path = relative(dirname(from), to).replace(/\\/g, "/")
  return path.startsWith(".") ? path : `./${path}`
}

/** Source of `.platform/entry.tsx`: the user entry, wrapped with `withTecton` when Tecton is enabled. */
export function renderEntry(config: ResolvedPlatformConfig): string {
  const userEntry = toImportPath(config.generatedEntry, config.entry).replace(
    /\.(tsx|ts|jsx|js)$/,
    ""
  )
  const lines = [GENERATED_BANNER, `import definition from "${userEntry}"`]
  if (config.tecton) {
    lines.push(
      `import { withTecton } from "@platform/mfe-react/tecton"`,
      "",
      "export default withTecton(definition)"
    )
  } else {
    lines.push("", "export default definition")
  }
  return `${lines.join("\n")}\n`
}

/** Fail early with a clear message when the canonical bootstrap file is missing. */
export function assertEntryExists(config: ResolvedPlatformConfig): void {
  if (existsSync(config.entry)) return
  const rel = relative(config.root, config.entry).replace(/\\/g, "/")
  throw new PlatformError({
    code: "INTERNAL",
    message: `The MFE bootstrap file "${rel}" does not exist. Every platform remote default-exports createMfe({ routeTree, widgets?, registrations? }) from ${rel} (from "@platform/mfe-react"); @platform/vite exposes it through the generated .platform/entry.tsx.`,
    owner: { mfeId: config.mfeId },
    source: rel,
    override: "mfe.config.ts → entry",
  })
}

/** Write `.platform/entry.tsx` (and `.platform/.gitignore`); returns the file path. Idempotent. */
export function writeGeneratedEntry(config: ResolvedPlatformConfig): string {
  assertEntryExists(config)
  ensurePlatformDir(config.root)
  mkdirSync(dirname(config.generatedEntry), { recursive: true })
  const content = renderEntry(config)
  if (
    !existsSync(config.generatedEntry) ||
    readFileSync(config.generatedEntry, "utf8") !== content
  )
    writeFileSync(config.generatedEntry, content)
  return config.generatedEntry
}
