/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WellsIndexRouteImport } from './routes/wells/index'
import { Route as WellsWellIdRouteImport } from './routes/wells/$wellId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsIndexRoute = WellsIndexRouteImport.update({
  id: '/wells/',
  path: '/wells/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellsWellIdRoute = WellsWellIdRouteImport.update({
  id: '/wells/$wellId',
  path: '/wells/$wellId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells/': typeof WellsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells': typeof WellsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/wells/$wellId': typeof WellsWellIdRoute
  '/wells/': typeof WellsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/wells/$wellId' | '/wells/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/wells/$wellId' | '/wells'
  id: '__root__' | '/' | '/settings' | '/wells/$wellId' | '/wells/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  WellsWellIdRoute: typeof WellsWellIdRoute
  WellsIndexRoute: typeof WellsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells/': {
      id: '/wells/'
      path: '/wells'
      fullPath: '/wells/'
      preLoaderRoute: typeof WellsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wells/$wellId': {
      id: '/wells/$wellId'
      path: '/wells/$wellId'
      fullPath: '/wells/$wellId'
      preLoaderRoute: typeof WellsWellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  WellsWellIdRoute: WellsWellIdRoute,
  WellsIndexRoute: WellsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
