import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { join } from "node:path"

import { validateManifest } from "@platform-internal/core"
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest"
import { build, createServer, type ViteDevServer } from "vite"

import { platform } from "../src/index"

// @module-federation/vite disables itself under test runners unless told otherwise.
process.env.MFE_VITE_NO_TEST_ENV_CHECK = "true"

const fixture = join(__dirname, "fixtures", "sample-mfe")
// The copy must stay inside the package so react, vite and the router resolve from node_modules.
const root = join(__dirname, ".tmp", `sample-mfe-${process.pid}`)

beforeAll(() => {
  rmSync(root, { recursive: true, force: true })
  mkdirSync(join(__dirname, ".tmp"), { recursive: true })
  cpSync(fixture, root, {
    recursive: true,
    filter: (source) =>
      !source.includes(`${fixture}/dist`) && !source.endsWith("routeTree.gen.ts"),
  })
})

afterAll(() => {
  rmSync(root, { recursive: true, force: true })
})

describe("vite build with the platform plugin", () => {
  it("emits the remote entry, the manifests and scoped CSS", async () => {
    await build({
      root,
      configFile: false,
      logLevel: "error",
      plugins: [platform({ root, test: false })],
      build: { outDir: "dist", emptyOutDir: true },
    })
    const dist = join(root, "dist")
    expect(existsSync(join(dist, "remoteEntry.js"))).toBe(true)
    expect(existsSync(join(dist, "mf-manifest.json"))).toBe(true)
    expect(existsSync(join(dist, "platform-manifest.json"))).toBe(true)
    expect(existsSync(join(root, ".platform", "entry.tsx"))).toBe(true)
    expect(existsSync(join(root, ".platform", "manifest.json"))).toBe(true)
    expect(existsSync(join(root, "src", "routeTree.gen.ts"))).toBe(true)
    expect(readFileSync(join(root, ".platform", "entry.tsx"), "utf8")).toContain(
      "Generated by @platform/vite"
    )

    const manifest = JSON.parse(readFileSync(join(dist, "platform-manifest.json"), "utf8"))
    const validation = validateManifest(manifest)
    expect(validation.ok).toBe(true)
    expect(manifest.mfeId).toBe("sample-mfe")
    expect(manifest.entry).toMatchObject({
      loader: "module-federation",
      name: "mfe_sample_mfe",
      file: "remoteEntry.js",
      expose: "./mfe",
      loaderManifest: "mf-manifest.json",
    })
    expect(manifest.dev).toBeUndefined()
    expect(manifest.routes).toHaveLength(3)
    expect(manifest.css.assets.length).toBeGreaterThan(0)

    const mfManifest = JSON.parse(readFileSync(join(dist, "mf-manifest.json"), "utf8"))
    expect(mfManifest.name).toBe("mfe_sample_mfe")
    expect(mfManifest.exposes.map((expose: { name: string }) => expose.name)).toContain("mfe")
    expect(mfManifest.shared.map((shared: { name: string }) => shared.name)).toEqual(
      expect.arrayContaining(["react", "react-dom", "@tanstack/react-router"])
    )

    const cssFiles = manifest.css.assets as string[]
    for (const file of cssFiles) expect(existsSync(join(dist, file))).toBe(true)
    // The minifier drops the attribute quotes: [data-mfe=sample-mfe].
    const owner = /\[data-mfe="?sample-mfe"?\]/
    const css = cssFiles.map((file) => readFileSync(join(dist, file), "utf8")).join("\n")
    expect(css).toMatch(owner)
    expect(css).toContain("--sample-accent")
    expect(css).toMatch(/\[data-mfe="?sample-mfe"?\] \.sample-card/)
    expect(css).toContain("mfe-sample-mfe-sample-fade")
    expect(css).not.toMatch(/(^|[\s{},;])(:root|html|body)[\s{,]/)
    expect(css).not.toContain("@font-face")
    // Every emitted stylesheet is scoped, not only the ones listed in the manifest.
    const walk = (dir: string): string[] =>
      readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
        entry.isDirectory() ? walk(join(dir, entry.name)) : [join(dir, entry.name)]
      )
    for (const file of walk(dist).filter((file) => file.endsWith(".css")))
      expect(readFileSync(file, "utf8")).toMatch(owner)
  })
})

describe("vite dev server with the platform plugin", () => {
  let server: ViteDevServer
  let origin: string

  beforeAll(async () => {
    server = await createServer({
      root,
      configFile: false,
      logLevel: "error",
      plugins: [platform({ root, test: false })],
      server: { host: "127.0.0.1" },
    })
    await server.listen()
    origin = new URL(server.resolvedUrls!.local[0]!).origin
  })

  afterAll(async () => {
    await server.close()
  })

  it("serves the development manifest with HMR metadata and CORS headers", async () => {
    const response = await fetch(`${origin}/platform-manifest.json`, {
      headers: { origin: "http://localhost:3000" },
    })
    expect(response.status).toBe(200)
    expect(response.headers.get("access-control-allow-origin")).toBe("*")
    expect(response.headers.get("cache-control")).toBe("no-store")
    const manifest = await response.json()
    expect(validateManifest(manifest).ok).toBe(true)
    expect(manifest.dev.hmr).toBe(true)
    expect(manifest.dev.origin).toBe(origin)
    expect(manifest.dev.refreshPreamble).toBe("/@platform/refresh-preamble")
    expect(manifest.dev.configHash).toMatch(/^[0-9a-f]{12}$/)
    expect(manifest.dev.restartRequired).toBeUndefined()
    expect(manifest.remote.baseUrl).toBe(`${origin}/`)
    expect(manifest.routes.map((route: { path: string }) => route.path)).toEqual([
      "/",
      "/assets/$assetId",
      "/settings",
    ])
  })

  it("serves the refresh preamble as a JS module", async () => {
    const response = await fetch(`${origin}/@platform/refresh-preamble`)
    expect(response.status).toBe(200)
    expect(response.headers.get("content-type")).toContain("javascript")
    expect(response.headers.get("access-control-allow-origin")).toBe("*")
    const code = await response.text()
    expect(code).toContain('import RefreshRuntime from "/@react-refresh"')
    expect(code).toContain("injectIntoGlobalHook(window)")
    expect(code).toContain("window.$RefreshReg$")
    expect(code).toContain("import.meta.url")
  })

  it("serves the remote entry and the React refresh runtime", async () => {
    const entry = await fetch(`${origin}/remoteEntry.js`)
    expect(entry.status).toBe(200)
    expect(await entry.text()).toContain("mfe_sample_mfe")
    const refresh = await fetch(`${origin}/@react-refresh`)
    expect(refresh.status).toBe(200)
  })

  it("flags restart-requiring changes in the manifest and over HMR", async () => {
    const sent = vi.spyOn(server.ws, "send")
    const packageJson = join(root, "package.json")
    const original = readFileSync(packageJson, "utf8")
    writeFileSync(packageJson, original.replace('"version": "1.2.3"', '"version": "1.2.4"'))
    try {
      let manifest:
        | { dev: { restartRequired?: boolean; restartReason?: string; configHash: string } }
        | undefined
      for (let attempt = 0; attempt < 100; attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, 100))
        manifest = (await (
          await fetch(`${origin}/platform-manifest.json`)
        ).json()) as typeof manifest
        if (manifest?.dev.restartRequired) break
      }
      expect(manifest?.dev.restartRequired).toBe(true)
      expect(manifest?.dev.restartReason).toContain("package.json")
      const event = sent.mock.calls
        .map(
          (call) =>
            call[0] as {
              type?: string
              event?: string
              data?: { reason: string; file: string }
            }
        )
        .find((payload) => payload?.event === "platform:restart-required")
      expect(event).toBeDefined()
      expect(event?.data).toMatchObject({ file: "package.json", mfeId: "sample-mfe" })
    } finally {
      writeFileSync(packageJson, original)
      sent.mockRestore()
    }
  })
})
