// Serves the built conformance remotes as static production artefacts and
// starts the SSR shell with runtime configuration generated by the host
// entrypoint from PLATFORM_* variables — the same path a Docker container takes.
import { spawn, spawnSync, type ChildProcess } from "node:child_process"
import { existsSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { conformanceEnv } from "../../scripts/conformance-env.mjs"
import { serveStatic } from "../../scripts/serve-static.mjs"
import { waitFor } from "../../scripts/wait-for.mjs"

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const shellOnWindows = process.platform === "win32"

declare global {
  var __platformE2E: { servers: { close(): void }[]; children: ChildProcess[] } | undefined
}

const remotes: [string, number][] = [
  ["apps/conformance-react19/dist", 4201],
  ["apps/conformance-react18/dist", 4202],
  ["apps/conformance-widget-a/dist", 4203],
  ["apps/conformance-widget-b/dist", 4204],
]

export default async function globalSetup() {
  const state = { servers: [] as { close(): void }[], children: [] as ChildProcess[] }
  globalThis.__platformE2E = state
  // PLATFORM_E2E_EXTERNAL=1: the shell and remotes are already running (local iteration).
  if (process.env.PLATFORM_E2E_EXTERNAL) {
    await waitFor("http://127.0.0.1:4100/", { timeoutMs: 30_000 })
    return
  }
  for (const [dir, port] of remotes) {
    const full = join(root, dir)
    if (!existsSync(join(full, "platform-manifest.json"))) {
      throw new Error(
        `${dir}/platform-manifest.json is missing — run \`pnpm build:all\` before \`pnpm e2e\`.`
      )
    }
    state.servers.push((await serveStatic(full, port)) as { close(): void })
  }
  // Runtime configuration through the Docker entrypoint (never rebuilds assets).
  const env = { ...process.env, ...conformanceEnv({ mode: "production" }) }
  const shellDir = join(root, "apps/conformance-shell")
  const configPath = join(shellDir, "dist", "client", "platform-config.json")
  mkdirSync(dirname(configPath), { recursive: true })
  const entrypoint = join(root, "packages/host/dist/entrypoint.js")
  const generated = spawnSync(
    process.execPath,
    [
      entrypoint,
      "--out",
      configPath,
      "--known",
      "asset-tracker,legacy-reports,widget-a,widget-b,unavailable-remote,disabled-remote",
    ],
    { env, encoding: "utf8" }
  )
  if (generated.status !== 0)
    throw new Error(`entrypoint failed: ${generated.stdout}\n${generated.stderr}`)
  if (!existsSync(join(shellDir, "dist", "server", "server.js")))
    throw new Error(
      "apps/conformance-shell/dist/server/server.js is missing — run `pnpm build:all` first."
    )
  // The built SSR shell is served by `vite preview` (the same handler a Node adapter would host).
  const viteBin = join(root, "node_modules", "vite", "bin", "vite.js")
  const child = spawn(
    process.execPath,
    [viteBin, "preview", "--port", "4100", "--strictPort", "--host", "127.0.0.1"],
    {
      cwd: shellDir,
      env: { ...env, PLATFORM_CONFIG_PATH: configPath },
      stdio: "pipe",
      shell: shellOnWindows,
    }
  )
  child.stdout?.on("data", (chunk) => process.stdout.write(`[shell] ${chunk}`))
  child.stderr?.on("data", (chunk) => process.stderr.write(`[shell] ${chunk}`))
  state.children.push(child)
  await waitFor("http://127.0.0.1:4100/", { timeoutMs: 90_000 })
  await waitFor("http://127.0.0.1:4201/platform-manifest.json")
}
