// Serves the built conformance remotes as static production artefacts and
// starts the SSR shell with runtime configuration generated by the host
// entrypoint from PLATFORM_* variables — the same path a Docker container takes.
import { spawn, spawnSync, type ChildProcess } from "node:child_process"
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { conformanceEnv } from "../../scripts/conformance-env.mjs"
import { serveStatic } from "../../scripts/serve-static.mjs"
import { waitFor } from "../../scripts/wait-for.mjs"

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..")
const shellOnWindows = process.platform === "win32"

declare global {
  // eslint-disable-next-line no-var
  var __platformE2E: { servers: { close(): void }[]; children: ChildProcess[] } | undefined
}

const remotes: [string, number][] = [
  ["apps/conformance-react19/dist", 4201],
  ["apps/conformance-react18/dist", 4202],
  ["apps/conformance-widget-a/dist", 4203],
  ["apps/conformance-widget-b/dist", 4204],
]

export default async function globalSetup() {
  const state = { servers: [] as { close(): void }[], children: [] as ChildProcess[] }
  globalThis.__platformE2E = state
  for (const [dir, port] of remotes) {
    const full = join(root, dir)
    if (!existsSync(join(full, "platform-manifest.json"))) {
      throw new Error(`${dir}/platform-manifest.json is missing — run \`pnpm build:all\` before \`pnpm e2e\`.`)
    }
    state.servers.push((await serveStatic(full, port)) as { close(): void })
  }
  // Runtime configuration through the Docker entrypoint (never rebuilds assets).
  const env = { ...process.env, ...conformanceEnv({ mode: "production" }) }
  const outputDir = join(root, "apps/conformance-shell/.output")
  const configPath = join(outputDir, "public", "platform-config.json")
  mkdirSync(dirname(configPath), { recursive: true })
  const entrypoint = join(root, "packages/host/dist/entrypoint.js")
  const generated = spawnSync(process.execPath, [entrypoint, "--out", configPath, "--known", "asset-tracker,legacy-reports,widget-a,widget-b,unavailable-remote,disabled-remote"], { env, encoding: "utf8" })
  if (generated.status !== 0) throw new Error(`entrypoint failed: ${generated.stdout}\n${generated.stderr}`)
  writeFileSync(join(root, "test-results-config-source.txt"), configPath)
  const server = join(outputDir, "server", "index.mjs")
  if (!existsSync(server)) throw new Error("apps/conformance-shell/.output/server/index.mjs is missing — run `pnpm build:all` first.")
  const child = spawn(process.execPath, [server], { cwd: join(root, "apps/conformance-shell"), env: { ...env, PORT: "4100", HOST: "127.0.0.1", PLATFORM_CONFIG_PATH: configPath, NITRO_PORT: "4100", NITRO_HOST: "127.0.0.1" }, stdio: "pipe", shell: shellOnWindows })
  child.stdout?.on("data", (chunk) => process.stdout.write(`[shell] ${chunk}`))
  child.stderr?.on("data", (chunk) => process.stderr.write(`[shell] ${chunk}`))
  state.children.push(child)
  await waitFor("http://127.0.0.1:4100/", { timeoutMs: 90_000 })
  await waitFor("http://127.0.0.1:4201/platform-manifest.json")
}
