import { existsSync, readFileSync, statSync } from "node:fs"
import type { IncomingMessage, ServerResponse } from "node:http"
import { basename, dirname, extname, join, normalize, relative, resolve, sep } from "node:path"

import { PlatformError, type MfeManifest } from "@platform-internal/core"
import pc from "picocolors"
import type { Plugin, ViteDevServer } from "vite"

import { generateManifest } from "../manifest"
import { findPackageJson } from "../project"
import { buildFederationConfig, resolvePlatformConfig, type ResolvedPlatformConfig } from "../resolve-config"
import { computeConfigHash, restartError, type PlatformContext } from "./context"

export const DEV_MANIFEST_PATH = "/platform-manifest.json"
export const REFRESH_PREAMBLE_PATH = "/@platform/refresh-preamble"
export const HARNESS_PATH = "/__platform/harness"
export const RESTART_EVENT = "platform:restart-required"

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
}

/** JS module a host page imports before loading a dev remote, so React Refresh is installed for the remote's own React runtime. */
export function renderRefreshPreamble(base: string): string {
  const runtime = `${base.endsWith("/") ? base : `${base}/`}@react-refresh`
  return `// Generated by @platform/vite — React Fast Refresh preamble for this remote's React instance.
import RefreshRuntime from "${runtime}"
const key = "__platform_refresh_preamble__" + import.meta.url
if (!globalThis[key]) {
  globalThis[key] = true
  RefreshRuntime.injectIntoGlobalHook(window)
}
if (!window.$RefreshReg$) {
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
}
window.__vite_plugin_react_preamble_installed__ = true
export default true
`
}

export function resolveHarnessDir(root: string, explicit?: string): string | undefined {
  if (explicit) return existsSync(explicit) ? explicit : undefined
  const hostPackage = findPackageJson(root, "@platform/host")
  if (!hostPackage) return undefined
  const dir = join(dirname(hostPackage), "dist", "harness")
  return existsSync(join(dir, "index.html")) ? dir : undefined
}

export function injectHarnessConfig(html: string, config: { manifestUrl: string; mfeId: string; origin?: string }): string {
  const script = `<script>window.__PLATFORM_HARNESS__ = ${JSON.stringify(config)}</script>`
  return html.includes("</head>") ? html.replace("</head>", `${script}\n</head>`) : `${script}\n${html}`
}

export function renderFallbackHarness(config: ResolvedPlatformConfig, manifestUrl: string): string {
  const title = `${config.displayName} — platform harness`
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<script>window.__PLATFORM_HARNESS__ = ${JSON.stringify({ manifestUrl, mfeId: config.mfeId })}</script>
<style>
body { font: 14px/1.5 system-ui, sans-serif; margin: 2rem auto; max-width: 60rem; padding: 0 1rem; color: #1a1a1a; }
code, pre { font-family: ui-monospace, monospace; }
pre { background: #f4f4f5; padding: 1rem; overflow: auto; border-radius: 6px; }
.notice { border-left: 4px solid #d97706; background: #fffbeb; padding: 0.75rem 1rem; }
</style>
</head>
<body>
<h1>${escapeHtml(config.displayName)} <small>(${escapeHtml(config.mfeId)})</small></h1>
<div class="notice">
<p><strong>The local shell harness is not installed.</strong> <code>@platform/host</code> (which ships the harness in <code>dist/harness</code>) is not resolvable from this project. Install it as a dev dependency (<code>pnpm add -D @platform/host</code>) or point <code>harness.dir</code> in <code>mfe.config.ts</code> at a built harness.</p>
<p>This remote is still fully usable from an SSR shell in development: point a manifest override at <a href="${escapeHtml(manifestUrl)}"><code>${escapeHtml(manifestUrl)}</code></a>.</p>
</div>
<h2>Development manifest</h2>
<pre id="manifest">loading…</pre>
<script type="module">
const pre = document.getElementById("manifest")
try {
  const response = await fetch(${JSON.stringify(manifestUrl)}, { cache: "no-store" })
  pre.textContent = JSON.stringify(await response.json(), null, 2)
} catch (error) {
  pre.textContent = "Could not load the manifest: " + (error && error.message ? error.message : String(error))
}
</script>
</body>
</html>
`
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char)
}

function send(res: ServerResponse, status: number, body: string | Buffer, contentType: string, extraHeaders: Record<string, string> = {}): void {
  res.statusCode = status
  res.setHeader("Content-Type", contentType)
  res.setHeader("Access-Control-Allow-Origin", "*")
  res.setHeader("Cache-Control", "no-store")
  for (const [key, value] of Object.entries(extraHeaders)) res.setHeader(key, value)
  res.end(body)
}

function requestOrigin(server: ViteDevServer, req: IncomingMessage): string | undefined {
  const local = server.resolvedUrls?.local[0]
  if (local) {
    try {
      return new URL(local).origin
    } catch {
      /* fall through */
    }
  }
  const host = req.headers.host
  if (!host) return undefined
  const protocol = server.config.server.https ? "https" : "http"
  return `${protocol}://${host}`
}

export interface DevState {
  configHash: string
  restartRequired: boolean
  restartReason?: string
  restartFile?: string
}

/**
 * Dev endpoints (`/platform-manifest.json`, `/@platform/refresh-preamble`,
 * `/__platform/harness/`), restart diagnostics for manifest-affecting changes
 * and the startup summary.
 */
export function platformDevPlugin(context: PlatformContext): Plugin {
  return {
    name: "platform:dev",
    apply: "serve",
    configureServer(server) {
      const config = context.config()
      const state: DevState = { configHash: context.configHash(), restartRequired: false }
      let manifestCache: { origin: string | undefined; manifest: MfeManifest } | undefined
      let manifestPromise: Promise<MfeManifest> | undefined
      const manifestUrl = `${server.config.base.replace(/\/$/, "")}${DEV_MANIFEST_PATH}`
      const harnessDir = config.harness.enabled ? resolveHarnessDir(config.root, config.harness.dir) : undefined

      const devManifest = async (origin: string | undefined): Promise<MfeManifest> => {
        if (manifestCache && manifestCache.origin === origin) return manifestCache.manifest
        manifestPromise ??= generateManifest({
          root: config.root,
          config,
          mode: "dev",
          dev: { origin, configHash: state.configHash, restartRequired: state.restartRequired || undefined, restartReason: state.restartReason },
        })
          .then((generated) => {
            for (const warning of generated.warnings) server.config.logger.warn(pc.yellow(`[platform] ${warning}`))
            manifestCache = { origin, manifest: generated.manifest }
            return generated.manifest
          })
          .finally(() => {
            manifestPromise = undefined
          })
        return manifestPromise
      }
      const invalidateManifest = () => {
        manifestCache = undefined
      }

      // Restart diagnostics: watch the restart-requiring inputs and compare the config hash.
      const watched = new Set([...config.dependencies, config.routeTreeFile, ...["mfe.config.ts", "mfe.config.mts", "mfe.config.js", "mfe.config.mjs"].map((name) => join(config.root, name))].map((file) => resolve(file)))
      for (const file of watched) if (existsSync(file)) server.watcher.add(file)
      let checking: Promise<void> | undefined
      const checkRestart = async (file: string) => {
        try {
          const next = await resolvePlatformConfig({ root: config.root, options: context.options, command: "serve" })
          const hash = computeConfigHash(next, buildFederationConfig(next))
          if (hash === state.configHash) return
          const rel = relative(config.root, file).replace(/\\/g, "/")
          const reason = basename(file) === "routeTree.gen.ts" ? `The generated route tree changed (${rel})` : `A manifest-affecting input changed (${rel})`
          state.configHash = hash
          state.restartRequired = true
          state.restartReason = reason
          state.restartFile = rel
          invalidateManifest()
          server.config.logger.warn(pc.yellow(restartError(config, file, reason).format()))
          server.ws.send({ type: "custom", event: RESTART_EVENT, data: { reason, file: rel, configHash: hash, mfeId: config.mfeId } })
        } catch (error) {
          const message = error instanceof PlatformError ? error.format() : error instanceof Error ? error.message : String(error)
          server.config.logger.error(pc.red(`[platform] could not re-evaluate the configuration after ${file} changed:\n${message}`))
        }
      }
      const onFsEvent = (file: string) => {
        invalidateManifest()
        const absolute = resolve(file)
        if (!watched.has(absolute)) return
        checking = (checking ?? Promise.resolve()).then(() => checkRestart(absolute))
      }
      server.watcher.on("change", onFsEvent)
      server.watcher.on("add", onFsEvent)
      server.watcher.on("unlink", onFsEvent)

      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? "/").split("?")[0] ?? "/"
        const base = server.config.base.replace(/\/$/, "")
        const path = base && url.startsWith(base) ? url.slice(base.length) || "/" : url
        if (req.method === "OPTIONS" && (path === DEV_MANIFEST_PATH || path === REFRESH_PREAMBLE_PATH || path.startsWith(`${HARNESS_PATH}/`))) {
          send(res, 204, "", "text/plain", { "Access-Control-Allow-Methods": "GET, OPTIONS", "Access-Control-Allow-Headers": "*" })
          return
        }
        if (path === DEV_MANIFEST_PATH) {
          const origin = requestOrigin(server, req)
          void devManifest(origin).then(
            (manifest) => send(res, 200, `${JSON.stringify(manifest, null, 2)}\n`, CONTENT_TYPES[".json"]!),
            (error: unknown) => {
              const message = error instanceof PlatformError ? error.format() : error instanceof Error ? error.message : String(error)
              server.config.logger.error(pc.red(`[platform] ${message}`))
              send(res, 500, JSON.stringify({ error: message }), CONTENT_TYPES[".json"]!)
            }
          )
          return
        }
        if (path === REFRESH_PREAMBLE_PATH) {
          send(res, 200, renderRefreshPreamble(server.config.base || "/"), CONTENT_TYPES[".js"]!)
          return
        }
        if (path === HARNESS_PATH) {
          res.statusCode = 302
          res.setHeader("Location", `${base}${HARNESS_PATH}/`)
          res.end()
          return
        }
        if (path.startsWith(`${HARNESS_PATH}/`)) {
          if (!config.harness.enabled) {
            send(res, 404, "The platform harness is disabled (harness.enabled = false).", CONTENT_TYPES[".txt"]!)
            return
          }
          const relativePath = decodeURIComponent(path.slice(HARNESS_PATH.length + 1)) || "index.html"
          if (!harnessDir) {
            if (relativePath === "index.html") send(res, 200, renderFallbackHarness(config, manifestUrl), CONTENT_TYPES[".html"]!)
            else send(res, 404, "Not found", CONTENT_TYPES[".txt"]!)
            return
          }
          const target = normalize(join(harnessDir, relativePath))
          if (!target.startsWith(`${normalize(harnessDir)}${sep}`) && target !== normalize(harnessDir)) {
            send(res, 403, "Forbidden", CONTENT_TYPES[".txt"]!)
            return
          }
          let file = target
          if (!existsSync(file) || statSync(file).isDirectory()) file = join(harnessDir, "index.html")
          if (!existsSync(file)) {
            send(res, 404, "Not found", CONTENT_TYPES[".txt"]!)
            return
          }
          const type = CONTENT_TYPES[extname(file).toLowerCase()] ?? "application/octet-stream"
          if (basename(file) === "index.html") {
            send(res, 200, injectHarnessConfig(readFileSync(file, "utf8"), { manifestUrl, mfeId: config.mfeId, origin: requestOrigin(server, req) }), type)
          } else send(res, 200, readFileSync(file), type)
          return
        }
        next()
      })

      const printSummary = () => {
        const origin = server.resolvedUrls?.local[0]?.replace(/\/$/, "")
        const routes = manifestCache?.manifest.routes.length
        const shared = config.shared.requests.filter((request) => request.shared).map((request) => request.name)
        const bundled = config.shared.requests.filter((request) => !request.shared).map((request) => request.name)
        const lines = [
          `${pc.bold("platform")} remote ${pc.cyan(config.mfeId)} (${config.mfeIdSource === "identity" ? "persisted identity" : config.mfeIdSource})`,
          `  route prefix   ${config.routePrefix}${routes !== undefined ? `  (${routes} route${routes === 1 ? "" : "s"})` : ""}`,
          `  shared         ${shared.length ? shared.join(", ") : "none"}${bundled.length ? pc.dim(`  bundled: ${bundled.join(", ")}`) : ""}`,
          `  capabilities   ${manifestCache?.manifest.capabilities.join(", ") ?? "(inferred on first request)"}`,
          `  tecton         ${config.tecton ? `on${config.tectonVersion ? ` (${config.tectonVersion})` : ""}` : "off"}${config.tailwind ? "  tailwind on" : ""}`,
          `  manifest       ${origin ?? ""}${manifestUrl}`,
          `  harness        ${config.harness.enabled ? `${origin ?? ""}${base(server)}${HARNESS_PATH}/${harnessDir ? "" : pc.dim("  (@platform/host not installed: fallback page)")}` : "disabled"}`,
        ]
        server.config.logger.info(`\n${lines.join("\n")}\n`)
      }
      let summarized = false
      const summarize = () => {
        if (summarized) return
        summarized = true
        void devManifest(server.resolvedUrls?.local[0] ? new URL(server.resolvedUrls.local[0]).origin : undefined).then(printSummary, printSummary)
      }
      // The Vite CLI prints its URLs once `resolvedUrls` is known; programmatic servers get a delayed fallback.
      const printUrls = server.printUrls.bind(server)
      server.printUrls = () => {
        printUrls()
        summarize()
      }
      if (server.httpServer) server.httpServer.once("listening", () => setTimeout(summarize, 100))
    },
  }
}

function base(server: ViteDevServer): string {
  return server.config.base.replace(/\/$/, "")
}
