import { existsSync } from "node:fs"
import type { IncomingMessage, ServerResponse } from "node:http"
import { basename, join, relative, resolve } from "node:path"

import { PlatformError, type MfeManifest } from "@platform-internal/core"
import pc from "picocolors"
import type { Plugin, ViteDevServer } from "vite"

import { generateManifest } from "../manifest"
import { buildFederationConfig, resolvePlatformConfig } from "../resolve-config"
import { computeConfigHash, restartError, type PlatformContext } from "./context"

export const DEV_MANIFEST_PATH = "/platform-manifest.json"
export const REFRESH_PREAMBLE_PATH = "/@platform/refresh-preamble"
export const RESTART_EVENT = "platform:restart-required"

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
}

/** JS module a host page imports before loading a dev remote, so React Refresh is installed for the remote's own React runtime. */
export function renderRefreshPreamble(base: string): string {
  const runtime = `${base.endsWith("/") ? base : `${base}/`}@react-refresh`
  return `// Generated by @platform/vite — React Fast Refresh preamble for this remote's React instance.
import RefreshRuntime from "${runtime}"
const key = "__platform_refresh_preamble__" + import.meta.url
if (!globalThis[key]) {
  globalThis[key] = true
  RefreshRuntime.injectIntoGlobalHook(window)
}
if (!window.$RefreshReg$) {
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
}
window.__vite_plugin_react_preamble_installed__ = true
export default true
`
}

function send(
  res: ServerResponse,
  status: number,
  body: string | Buffer,
  contentType: string,
  extraHeaders: Record<string, string> = {}
): void {
  res.statusCode = status
  res.setHeader("Content-Type", contentType)
  res.setHeader("Access-Control-Allow-Origin", "*")
  res.setHeader("Cache-Control", "no-store")
  for (const [key, value] of Object.entries(extraHeaders)) res.setHeader(key, value)
  res.end(body)
}

function requestOrigin(server: ViteDevServer, req: IncomingMessage): string | undefined {
  const local = server.resolvedUrls?.local[0]
  if (local) {
    try {
      return new URL(local).origin
    } catch {
      /* fall through */
    }
  }
  const host = req.headers.host
  if (!host) return undefined
  const protocol = server.config.server.https ? "https" : "http"
  return `${protocol}://${host}`
}

export interface DevState {
  configHash: string
  restartRequired: boolean
  restartReason?: string
  restartFile?: string
}

/**
 * Dev endpoints (`/platform-manifest.json`, `/@platform/refresh-preamble`),
 * restart diagnostics for manifest-affecting changes and the startup summary.
 */
export function platformDevPlugin(context: PlatformContext): Plugin {
  return {
    name: "platform:dev",
    apply: (_config, env) => env.command === "serve" && env.mode !== "test",
    configureServer(server) {
      const config = context.config()
      const state: DevState = { configHash: context.configHash(), restartRequired: false }
      let manifestCache: { origin: string | undefined; manifest: MfeManifest } | undefined
      let manifestPromise: Promise<MfeManifest> | undefined
      const manifestUrl = `${server.config.base.replace(/\/$/, "")}${DEV_MANIFEST_PATH}`

      const devManifest = async (origin: string | undefined): Promise<MfeManifest> => {
        if (manifestCache && manifestCache.origin === origin) return manifestCache.manifest
        manifestPromise ??= generateManifest({
          root: config.root,
          config,
          mode: "dev",
          dev: {
            origin,
            configHash: state.configHash,
            restartRequired: state.restartRequired || undefined,
            restartReason: state.restartReason,
          },
        })
          .then((generated) => {
            for (const warning of generated.warnings)
              server.config.logger.warn(pc.yellow(`[platform] ${warning}`))
            manifestCache = { origin, manifest: generated.manifest }
            return generated.manifest
          })
          .finally(() => {
            manifestPromise = undefined
          })
        return manifestPromise
      }
      const invalidateManifest = () => {
        manifestCache = undefined
      }

      // Restart diagnostics: watch the restart-requiring inputs and compare the config hash.
      const watched = new Set(
        [
          ...config.dependencies,
          config.routeTreeFile,
          ...["mfe.config.ts", "mfe.config.mts", "mfe.config.js", "mfe.config.mjs"].map(
            (name) => join(config.root, name)
          ),
        ].map((file) => resolve(file))
      )
      for (const file of watched) if (existsSync(file)) server.watcher.add(file)
      let checking: Promise<void> | undefined
      const checkRestart = async (file: string) => {
        try {
          const next = await resolvePlatformConfig({
            root: config.root,
            options: context.options,
            command: "serve",
          })
          const hash = computeConfigHash(next, buildFederationConfig(next))
          if (hash === state.configHash) return
          const rel = relative(config.root, file).replace(/\\/g, "/")
          const reason =
            basename(file) === "routeTree.gen.ts"
              ? `The generated route tree changed (${rel})`
              : `A manifest-affecting input changed (${rel})`
          state.configHash = hash
          state.restartRequired = true
          state.restartReason = reason
          state.restartFile = rel
          invalidateManifest()
          server.config.logger.warn(pc.yellow(restartError(config, file, reason).format()))
          server.ws.send({
            type: "custom",
            event: RESTART_EVENT,
            data: { reason, file: rel, configHash: hash, mfeId: config.mfeId },
          })
        } catch (error) {
          const message =
            error instanceof PlatformError
              ? error.format()
              : error instanceof Error
                ? error.message
                : String(error)
          server.config.logger.error(
            pc.red(
              `[platform] could not re-evaluate the configuration after ${file} changed:\n${message}`
            )
          )
        }
      }
      const onFsEvent = (file: string) => {
        invalidateManifest()
        const absolute = resolve(file)
        if (!watched.has(absolute)) return
        checking = (checking ?? Promise.resolve()).then(() => checkRestart(absolute))
      }
      server.watcher.on("change", onFsEvent)
      server.watcher.on("add", onFsEvent)
      server.watcher.on("unlink", onFsEvent)

      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? "/").split("?")[0] ?? "/"
        const base = server.config.base.replace(/\/$/, "")
        const path = base && url.startsWith(base) ? url.slice(base.length) || "/" : url
        if (
          req.method === "OPTIONS" &&
          (path === DEV_MANIFEST_PATH || path === REFRESH_PREAMBLE_PATH)
        ) {
          send(res, 204, "", "text/plain", {
            "Access-Control-Allow-Methods": "GET, OPTIONS",
            "Access-Control-Allow-Headers": "*",
          })
          return
        }
        if (path === DEV_MANIFEST_PATH) {
          const origin = requestOrigin(server, req)
          void devManifest(origin).then(
            (manifest) =>
              send(res, 200, `${JSON.stringify(manifest, null, 2)}\n`, CONTENT_TYPES[".json"]!),
            (error: unknown) => {
              const message =
                error instanceof PlatformError
                  ? error.format()
                  : error instanceof Error
                    ? error.message
                    : String(error)
              server.config.logger.error(pc.red(`[platform] ${message}`))
              send(res, 500, JSON.stringify({ error: message }), CONTENT_TYPES[".json"]!)
            }
          )
          return
        }
        if (path === REFRESH_PREAMBLE_PATH) {
          send(
            res,
            200,
            renderRefreshPreamble(server.config.base || "/"),
            CONTENT_TYPES[".js"]!
          )
          return
        }
        next()
      })

      const printSummary = () => {
        const origin = server.resolvedUrls?.local[0]?.replace(/\/$/, "")
        const routes = manifestCache?.manifest.routes.length
        const shared = config.shared.requests
          .filter((request) => request.shared)
          .map((request) => request.name)
        const bundled = config.shared.requests
          .filter((request) => !request.shared)
          .map((request) => request.name)
        const lines = [
          `${pc.bold("platform")} remote ${pc.cyan(config.mfeId)} (${config.mfeIdSource === "identity" ? "persisted identity" : config.mfeIdSource})`,
          `  route prefix   ${config.routePrefix}${routes !== undefined ? `  (${routes} route${routes === 1 ? "" : "s"})` : ""}`,
          `  shared         ${shared.length ? shared.join(", ") : "none"}${bundled.length ? pc.dim(`  bundled: ${bundled.join(", ")}`) : ""}`,
          `  capabilities   ${manifestCache?.manifest.capabilities.join(", ") ?? "(inferred on first request)"}`,
          `  tecton         ${config.tecton ? `on${config.tectonVersion ? ` (${config.tectonVersion})` : ""}` : "off"}${config.tailwind ? "  tailwind on" : ""}`,
          `  manifest       ${origin ?? ""}${manifestUrl}`,
        ]
        server.config.logger.info(`\n${lines.join("\n")}\n`)
      }
      let summarized = false
      const summarize = () => {
        if (summarized) return
        summarized = true
        void devManifest(
          server.resolvedUrls?.local[0]
            ? new URL(server.resolvedUrls.local[0]).origin
            : undefined
        ).then(printSummary, printSummary)
      }
      // The Vite CLI prints its URLs once `resolvedUrls` is known; programmatic servers get a delayed fallback.
      const printUrls = server.printUrls.bind(server)
      server.printUrls = () => {
        printUrls()
        summarize()
      }
      if (server.httpServer)
        server.httpServer.once("listening", () => setTimeout(summarize, 100))
    },
  }
}
